import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import AboutUs from "../containers/AboutUs/AboutUs";
import Chef from "../containers/Chef/Chef";
import FindUs from "../containers/Findus/FindUs";
import Footer from "../containers/Footer/Footer";
import Gallery from "../containers/Gallery/Gallery";
import Header from "../containers/Header/Header";
import Intro from "../containers/Intro/Intro";
import Laurels from "../containers/Laurels/Laurels";
import SpecialMenu from "../containers/Menu/SpecialMenu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <AboutUs />
      <SpecialMenu />
      <Chef />
      {/* <Intro /> */}
      {/* <Laurels /> */}
      {/* <Intro /> */}
      {/* <Laurels /> */}
      <Gallery />
      <FindUs />
      <Footer />
    </div>
  );
}
